### ISSUE TITLE
x = if cond then y else z;

### ISSUE THREAD

**Issue by thorade** [mtiller/ModelicaBook#338]
The `if...elseif...else...end if` statement is described here:
http://book.xogeny.com/behavior/discrete/if/

Maybe in the same section it should be menitoned that sometimes there are two possiblities to write the statement:

``` Modelica
if cond then 
  x=y;
else
  x=z;
end if;
```

versus

``` Modelica
x = if cond then y else z;
```

where the second approach has the advantage that it can be inlined.

**Comment by thorade** [comment]
The same is valied for for-loops:
http://book.xogeny.com/behavior/arrays/looping/#for

```
for i in 1:n loop
    x[i] := i^2;
  end for;
```
versus
```
x = {i^2 for i in 1:n};
```
But this is used and mentioned in the array chapter already.

**Comment by mtiller** [comment]
I've updated these sections.  Previews of the new text can be found [here](https://mbe-preview.modelica.university/behavior/discrete/if/) and [here](https://mbe-preview.modelica.university/behavior/arrays/construction/#array-comprehensions).  They will appear in the next release.
