### ISSUE TITLE
Not all variables are displayed in the plots

### ISSUE THREAD

**Issue by dietmarw** [mtiller/ModelicaBook#383]
I noticed that some plots don't display all variables as present in the legend. It might be sometimes that they are simply on top of each other but in this case the plot style should probably be changed.
Examples are: 
 - [ ] http://beta.book.xogeny.com/_images/TCB.svg from http://beta.book.xogeny.com/components/architectures/thermal_control/
 - [ ] http://beta.book.xogeny.com/_images/LVQM.svg from http://beta.book.xogeny.com/behavior/equations/population/
 - [ ] http://beta.book.xogeny.com/_images/SSI.svg from http://beta.book.xogeny.com/behavior/discrete/sampling/
 - [ ] http://beta.book.xogeny.com/_images/Eval1.svg and http://beta.book.xogeny.com/_images/Diff2.svg from http://beta.book.xogeny.com/behavior/functions/polynomial/
 - [ ]  http://beta.book.xogeny.com/_images/SMD_GG.svg and http://beta.book.xogeny.com/_images/SMD_GC_g.svg  (and perhaps also http://beta.book.xogeny.com/_images/SMD_GC_u.svg) and http://beta.book.xogeny.com/_images/SMD_CG.svg in http://beta.book.xogeny.com/components/components/rot_comps_adv/
 - [ ] http://beta.book.xogeny.com/_images/FSWB_comp.svg in http://beta.book.xogeny.com/components/subsystems/gear/
 - [ ] http://beta.book.xogeny.com/_images/AFS.svg in http://beta.book.xogeny.com/components/architectures/sensor_comparison/
 - [ ] http://beta.book.xogeny.com/_images/SV1.svg and http://beta.book.xogeny.com/_images/SV2.svg and http://beta.book.xogeny.com/_images/SV2T.svg in http://beta.book.xogeny.com/components/architectures/sensor_comparison_ad/
 - [ ] http://beta.book.xogeny.com/_images/TCB.svg and http://beta.book.xogeny.com/_images/TCE.svg and http://beta.book.xogeny.com/_images/TCE_BB.svg  and http://beta.book.xogeny.com/_images/TCE_Hy.svg in http://beta.book.xogeny.com/components/architectures/thermal_control/

**Comment by mtiller** [comment]
As far as I can tell, these are all cases where the lines overlap.  I see two ways of dealing with this.  the first is to simply eliminate overlapping signals.  These are effectively aliases and, as such, we can reduce it down until there are no aliases.  The other approach is to change the styling of the lines so that some are, for example, thin and dashed while others are fat and solid.  If rendered in the right order, all should be visible.

Comments?

**Comment by mtiller** [comment]
I've made what I think are the necessary styling changes.  Wait to see the preview before I judge whether the changes were correct.

**Comment by mtiller** [comment]
OK, this is fixed...somewhat.  Not 100% happy with the appearance in the interactive plots, but it will do for now.
