### ISSUE TITLE
Include full TOC in side bar?

### ISSUE THREAD

**Issue by xogeny** [mtiller/ModelicaBook#387]

**Comment by dietmarw** [comment]
**Very** good idea. I always struggle to navigate the webpage especially when trying to match the source files to it :-)

**Comment by xogeny** [comment]
Keep in mind, the search works (although I'm planning to improve it further).

**Comment by dietmarw** [comment]
Search does not help for navigation though.

**Comment by mtiller** [comment]
Done.
