### ISSUE TITLE
Unknown command "serve" in MakeFile

### ISSUE THREAD

**Issue by dietmarw** [mtiller/ModelicaBook#395]
I came across the make rule "serve" which is supposed to launch a command `serve` but that does not exist (at least not on Linux). Just a typo or something Mac specific?

https://github.com/xogeny/ModelicaBook/blob/8c5a7db0d76309a846943899366d80b0ed0575af/Makefile#L53-L54

**Comment by xogeny** [comment]
Yep, this is a simple web server for Node.js.  You can install it with `npm install -g serve`.  But I'll keep this open so we can incorporate it into the `book-builder` image so we can actually serve using the Docker container.

**Comment by dietmarw** [comment]
Ah I see. In that case let me test it and I might then simply add a PR

**Comment by xogeny** [comment]
This rule should be updated so that the `serve` rule not only uses the `book-builder` image, but that it serves the `dist` directory generated by the `generator` package.

**Comment by dietmarw** [comment]
I've added now a "serve" rule but the npm serve seems not to be suitable to serve the complex landing page. That looks like this: 
![image](https://user-images.githubusercontent.com/9332/34938011-0c417194-f9e7-11e7-943c-0c32a061b3ca.png)

This is **after** make site was run. @mtiller could you check if `serve` would for for you?

**Comment by xogeny** [comment]
I've seen this as well.  It has something to do with the server, I agree.  It may be that there is some tweak to either the configuration or the HTML that will get it working (although neither should be necessary).  Using a different static server (e.g., Python's built-in one) is, of course, an alternative.

**Comment by mtiller** [comment]
Since the HTML is generated a completely different way and because it can be generated easily enough with `yarn dev` in the `nextgen` directory, I'm closing this.
