### ISSUE TITLE
Switch to Stripe for payments?

### ISSUE THREAD

**Issue by xogeny** [mtiller/ModelicaBook#408]
It would be a big improvement if the payment system could actually send out an email automatically to purchasers with the links.  Shockingly, PayPal cannot do that.

Along the way, see if we can set a minimum payment.  Frequently, people pay $1.00 (or less!) for the book and I end up getting $0.00 because of fees.

**Comment by mtiller** [comment]
I decided to use PayHip.  It has lots of good features (mailing list integration, uses Stripe, automatically opens up access to digital content upon purchase, minimum pricing).  Basically, there is nothing manual left to do for me know.
