### ISSUE TITLE
Update ModelicaByExample to MSL v3.2.3

### ISSUE THREAD

**Issue by tbeu** [mtiller/ModelicaBook#414]
Similar issue as #355.

* The [constant](http://book.xogeny.com/components/packages/msl/#constants) of N_A should be updated.
* The [constant](http://book.xogeny.com/components/packages/msl/#constants) of q should be added.
* ModelicaByExample can be updated to use [MSL v3.2.3](https://github.com/modelica/ModelicaStandardLibrary/releases/tag/v3.2.3).

**Comment by dietmarw** [comment]
This should not be done until at least Dymola and OpenModelica release a version that ships v3.2.3 by default.

**Comment by tbeu** [comment]
The book issues can, the library issue should wait probably.

**Comment by tbeu** [comment]
Dymola 2020 ships MSL v3.2.3.

**Comment by Satinelamp** [comment]
Dymola 2021X ships MSL v4.0.0
