### ISSUE TITLE
Add PDF Bookmarks

### ISSUE THREAD

**Issue by mtiller** [mtiller/ModelicaBook#426]
I found a possible solution to this here:

https://tex.stackexchange.com/questions/346412/how-do-i-create-bookmarks-with-pdflatex

**Comment by thorade** [comment]
Would this be helpful?
https://tex.stackexchange.com/questions/42343/how-to-add-a-navigation-window-to-a-latex-generated-pdf-document/42350#42350

**Comment by mtiller** [comment]
I think 12803282b0340b64e67533e0db6475d211c99073 is the best solution (thanks @thorade).  The original request was for bookmarks and this is just a table of contents.  But I think ultimately this is the best I can hope for since bookmarks are, presumably, something that have to added manually and are meant for manual notation by the reader.  Using the table of contents maps well onto the structure of the book so I think it is sufficient.
