### ISSUE TITLE
https://mbe.modelica.university/behavior/functions/func_def/CallingFunctions

### ISSUE THREAD

**Issue by Helarga** [mtiller/ModelicaBook#437]
In the chapter of Functions definitions:
https://mbe.modelica.university/behavior/functions/func_def/#default-input-arguments
function PotentialEnergy
  input Real m "mass";
  input Real h "height";
  input Real g=9.81 "gravity";
  output Real pe "potential energy";
algorithm
  pe := m*g*h;
end PotentialEnergy;
----------------------------------------------------------------
and in:
https://mbe.modelica.university/behavior/functions/func_def/#calling-functions
PotentialEnergy(0.5, 1.0)             // m=1.0, h=0.5, g=9.81
------------------------------------------------------------------
I think the comment should be  // m=0.5, h=1.0, g=9.81

**Comment by dietmarw** [comment]
Thanks, I've prepared a PR in #438
